
#ifndef ANNOTATIONPLUGIN_EXPORT_H
#define ANNOTATIONPLUGIN_EXPORT_H

#ifdef ANNOTATIONPLUGIN_STATIC_DEFINE
#  define ANNOTATIONPLUGIN_EXPORT
#  define ANNOTATIONPLUGIN_NO_EXPORT
#else
#  ifndef ANNOTATIONPLUGIN_EXPORT
#    ifdef AnnotationPlugin_EXPORTS
        /* We are building this library */
#      define ANNOTATIONPLUGIN_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define ANNOTATIONPLUGIN_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef ANNOTATIONPLUGIN_NO_EXPORT
#    define ANNOTATIONPLUGIN_NO_EXPORT 
#  endif
#endif

#ifndef ANNOTATIONPLUGIN_DEPRECATED
#  define ANNOTATIONPLUGIN_DEPRECATED __declspec(deprecated)
#endif

#ifndef ANNOTATIONPLUGIN_DEPRECATED_EXPORT
#  define ANNOTATIONPLUGIN_DEPRECATED_EXPORT ANNOTATIONPLUGIN_EXPORT ANNOTATIONPLUGIN_DEPRECATED
#endif

#ifndef ANNOTATIONPLUGIN_DEPRECATED_NO_EXPORT
#  define ANNOTATIONPLUGIN_DEPRECATED_NO_EXPORT ANNOTATIONPLUGIN_NO_EXPORT ANNOTATIONPLUGIN_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef ANNOTATIONPLUGIN_NO_DEPRECATED
#    define ANNOTATIONPLUGIN_NO_DEPRECATED
#  endif
#endif

#endif /* ANNOTATIONPLUGIN_EXPORT_H */
